// <auto-generated />
namespace Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeblogtoarticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeblogtoarticle));
        
        string IMigrationMetadata.Id
        {
            get { return "202101272110513_change-blog-to-article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
