// <auto-generated />
namespace NinjaDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _01022019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01022019));
        
        string IMigrationMetadata.Id
        {
            get { return "202101262209585_01-02-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
