// <auto-generated />
namespace NinjaDomain.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addbirthdaytoninja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbirthdaytoninja));
        
        string IMigrationMetadata.Id
        {
            get { return "202101261630238_add-birthday-to-ninja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
